name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Обновленная версия checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Генерация змейки с правильными параметрами для v3
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: daniilt23
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Show status
        run: git status

      # Push изменений в main ветку
      - name: Push changes to main
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true

      # Деплой на GitHub Pages ветку
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
