name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Обновленная версия checkout
      - uses: actions/checkout@v4

      # Генерация змейки
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: daniilt23
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      - run: git status

      # Push изменений - ОБНОВЛЕННЫЙ СИНТАКСИС
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Деploy на GitHub Pages - ОБНОВЛЕННЫЙ СИНТАКСИС
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          force_orphan: true
